version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/js'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'deps(npm)'
    labels:
      - 'javascript'
    groups:
      js:
        patterns:
          - '*'
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'deps(cargo)'
    labels:
      - 'rust'
    groups:
      rust:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/docs'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'deps(pip)'
    groups:
      pip:
        patterns:
          - '*'
