version: 2
updates:
  - package-ecosystem: npm
    directories: ['/', '/js/client', '/js/extension']
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(npm)'
    labels:
      - javascript
    groups:
      js:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(cargo)'
    labels:
      - rust
    groups:
      rust:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: '/docs'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(pip)'
    groups:
      pip:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(ci)'
    groups:
      ci:
        patterns:
          - '*'
