name: JS PR

on:
  pull_request:
    branches: [master]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'javascript')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          working-directory: js
      - run: npm i && npm run test && npm run build
        working-directory: js
