name: win-gsmtc

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-lint:
    name: Build, Lint, and Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build -p win-gsmtc
      - name: Clippy
        run: cargo clippy -p win-gsmtc
      - name: Test
        run: cargo test -p win-gsmtc --doc
