name: Rust PR

on:
  pull_request:
    branches: [master]
    types: [labeled, opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'rust')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust_chain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}-build
      - run: cargo check --release
  check-format:
    if: contains(github.event.pull_request.labels.*.name, 'rust')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
